sudo: required

services:
  - docker

before_install:
  - docker build -t devhub/complex-client -f /client/Dockerfile.dev ./client

script:
  - docker run devhub/complex-client npm run test -- --coverage

after_success:
  # Build Images

  - docker build -t devhub/complex-client ./client
  - docker build -t devhub/complex-nginx ./nginx
  - docker build -t devhub/complex-server ./server
  - docker build -t devhub/complex-worker ./worker

  # Login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push devhub/complex-client
  - docker push devhub/complex-nginx
  - docker push devhub/complex-server
  - docker push devhub/complex-worker
