sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t digglepress/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run digglepress/react-test npm test -- --coverage

after_success:
  - docker build -t digglepress/multi-client ./client
  - docker build -t digglepress/multi-nginx ./nginx
  - docker build -t digglepress/multi-server ./server
  - docker build -t digglepress/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push digglepress/multi-client
  - docker push digglepress/multi-nginx
  - docker push digglepress/multi-server
  - docker push digglepress/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-495751004526
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
